apiVersion: apps/v1
kind: Deployment
metadata:
  name: myhttpd-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myhttpd
  template:
    metadata:
      labels:
        app: myhttpd
    spec:
      containers:
      - name: myhttpd-pod
        image: 211.183.3.10:5000/myhttpd:1.0
        ports:
        - containerPort: 80
